### ISSUE TITLE
Use "nf-seti-tex" for .tex extension

### ISSUE THREAD

**Issue by dr-scsi** [rainstormstudio/nerd-icons.el#15]
Many thanks for providing this package and my apologies if my comment is off; I'm not familiar with the code and a new user, so bear with me.

May I suggest to change the icon for `.tex` files from the current value in `nerd-icons-extension-icon-alist`:
https://github.com/rainstormstudio/nerd-icons.el/blob/aec48fe8e5296fa8367fcdc988ab846651d9e82a/nerd-icons.el#L379

to
```
("tex" nerd-icons-sucison "nf-seti-tex" :face nerd-icons-red)
```
And while we're at, I suggest to add these 2 extensions as well:

```
("ltx" nerd-icons-sucison "nf-seti-tex" :face nerd-icons-red)
("dtx" nerd-icons-sucison "nf-seti-tex" :face nerd-icons-red)
```
Is there also a reason why these lines are commented out?
https://github.com/rainstormstudio/nerd-icons.el/blob/aec48fe8e5296fa8367fcdc988ab846651d9e82a/nerd-icons.el#L719-L721

`latex-ts-mode` is clear since not available yet (AFAIK), but the first 2 can be changed to the values above, IIUC.

**Comment by dr-scsi** [comment]
Many thanks for your quick response.  I tried and it works.  But I realized that I've missed some entries, so I made a PR (#16).  Maybe you want to install it as well.  TIA.

**Comment by rainstormstudio** [comment]
Thank you for your contribution! I just merged your PR :)
