### ISSUE TITLE
` nerd-icons-icon-for-mode` fail if no icon assosiated with the major mode.

### ISSUE THREAD

**Issue by jilen** [rainstormstudio/nerd-icons.el#23]
Maybe a default icon should be used if no associated icon found.

**Comment by seagle0128** [comment]
You may need `nerd-icons-icon-for-buffer`, or handle `nerd-icons-icon-for-mode` yourself.

**Comment by rainstormstudio** [comment]
Hello could you please check if ab3ad9e81dba844bcd3669d6cc18524ae4af1ab1 fixes this?

**Comment by jilen** [comment]
Yes it is fixed.
