### ISSUE TITLE
Wrong reference to nf-oct-settings

### ISSUE THREAD

**Issue by il-santo** [rainstormstudio/nerd-icons.el#28]
https://github.com/rainstormstudio/nerd-icons.el/blob/c5a859f2033e22a0e38f9e77c92d162f997c5dc9/nerd-icons.el#L589

It should be:

`    (Custom-mode                       nerd-icons-codicon "nf-cod-settings"            )`

**Comment by seagle0128** [comment]
Closed by 9e8cece99bf6a55783c436d1650f8f6d1a86d1c3
