### ISSUE TITLE
Document how Symbols Nerd Fonts Mono is generated

### ISSUE THREAD

**Issue by jimeh** [rainstormstudio/nerd-icons.el#32]
I have had a bit of poke around, but couldn't find any reference to the how the font is created.

I'm asking, cause none of the official Nerd Fonts, nor any variants I generate myself (Mono, normal, Propo) have the same icon size/width as `Symbols Nerd Fonts Mono`, making them all look a little "off", while `Symbols Nerd Fonts Mono` looks perfect.

Mostly this is so that I can have icons look right when running Emacs in a terminal where I use a Nerd Font variant I generate myself.

Thanks :)

**Comment by rainstormstudio** [comment]
[Nerd Font Release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.1) calls it "NerdFontsSymbolsOnly". It contains `Symbols Nerd Font` and `Symbols Nerd Font Mono`. I'm simply using the font from the official release.

The benefit of using this is that it includes the variable width of the fonts when compiling it, which fixes some clipped issues. Reference: https://github.com/ryanoasis/nerd-fonts/issues/442#issuecomment-1263358904
Based on the reference above, if you want to include the variable width for your font patch, you need to use `--variable-width-glyph` when you patch your font.

**Comment by jimeh** [comment]
Thanks, that's really useful, and points me towards where to investigate next.

Annoyingly my custom patched font that uses `--variable-width-glyph` doesn't properly match the style of the symbols font. I'll dig deeper and see what I can find. As for this issue, I'm happy to close it :)
