### ISSUE TITLE
symbol's function definition is void nerd-icons-codicon

### ISSUE THREAD

**Issue by wereket** [rainstormstudio/nerd-icons.el#40]
symbol's function definition is void nerd-icons-codicon

**Comment by rainstormstudio** [comment]
Hello are you using this function interactively or in lisp script?

**Comment by wereket** [comment]
I just pasted the snippet in my config in completion section
https://github.com/wereket/dotfiles/blob/main/dot_emacs.d/config.org#completion

But I think it's on fresh reinstall of my config I have the issue, after I commented the snippet, when my install is finished, when I uncomment, it works now.

Thank you
