### ISSUE TITLE
Can we set some icon for ledger mode files ?

### ISSUE THREAD

**Issue by justinjk007** [rainstormstudio/nerd-icons.el#45]
I like to name my ledger files `*.ledger` , it would be nice to have some kinda icon for these files.

I know a lot people like to name them as `*.dat` too. 

Here are some suggestions I come up with 

`nf-md-piggy_bank_outline` 

`nf-md-file_table_outline`

`nf-md-file_table`

**Comment by seagle0128** [comment]
PRs are welcome 😄

**Comment by justinjk007** [comment]
I opened a PR. 
![Screenshot 2023-08-10 at 5 54 51 PM](https://github.com/rainstormstudio/nerd-icons.el/assets/12916795/7b3cf417-76ae-4508-baab-52c5edd97338)

Slightly unrelated,  I noticed org-mode icon seems to be defined twice.

**Comment by justinjk007** [comment]
I should say I have never really done much development with elisp and couldn't workout how to test my change. It was so small I thought it should be ok. 

Some guidance there should be great. I tried `eval-defun` on that block and it didn't work.

**Comment by seagle0128** [comment]
>Slightly unrelated, I noticed org-mode icon seems to be defined twice.

I've deleted it in 8f0d9a3.
