### ISSUE TITLE
Missing powerline symbol

### ISSUE THREAD

**Issue by LeoGitHuber** [rainstormstudio/nerd-icons.el#5]
![powerline](https://user-images.githubusercontent.com/50997355/230296567-7bae56f1-1b6e-49c2-9bc5-483cff8373be.png)
Are these symbols missing in this package?

**Comment by rainstormstudio** [comment]
Sorry I forgot to add Powerline glyphs to data list. It is fixed now: 6135f7474756c975cbcb8ea2748597d2c1ae7c22

Please update your local repo and use `nerd-icons-insert-powerline` to check if these symbols exist.

**Comment by LeoGitHuber** [comment]
Thanks, it works.
