### ISSUE TITLE
How to deal with backup files

### ISSUE THREAD

**Issue by Thaodan** [rainstormstudio/nerd-icons.el#51]
Programs create various backup files by append `.bak`, `.old` or `~`.
How should these be handled? Use the icon matching with to the file type or
one for backup files.

**Comment by rainstormstudio** [comment]
![image](https://github.com/rainstormstudio/nerd-icons.el/assets/22017420/95928dd3-2da9-4c09-8765-ee3a23ebe846)
do you think this icon is good for backups?

**Comment by Thaodan** [comment]
![Screenshot_20230902_022450](https://github.com/rainstormstudio/nerd-icons.el/assets/1747359/cfd976e1-23cf-4053-bb3d-a2fbc5f514a9)
I would prefer something similar to this one.

**Comment by seagle0128** [comment]
How about these?

<img width="137" alt="image" src="https://github.com/rainstormstudio/nerd-icons.el/assets/140797/e06349e2-1cde-4dc2-91c3-f621b8731d34">

<img width="147" alt="image" src="https://github.com/rainstormstudio/nerd-icons.el/assets/140797/dd7b05a6-0e00-414d-94ef-d4e2467acd31">

**Comment by Thaodan** [comment]
Looks good.

**Comment by rainstormstudio** [comment]
please check 1428e0de11e233d4fbb11ed15067f73d5f5ed958, basically I use `nf-md-file_restore` for backup icon. Note that `~` is for locked files so I ignored it here.
