### ISSUE TITLE
Dependency inconsistency with doom-modeline on Stable Melpa

### ISSUE THREAD

**Issue by xgqt** [rainstormstudio/nerd-icons.el#52]
Hello!

The package `doom-modeline` has a dependency on `nerd-icons` and is released on the Stable Melpa, but `nerd-icons` did not tag any release. 
Because of this installing `doom-modeline` will fail if a user has only Stable Melpa enabled.

Please tag a release to prevent this error.
Thanks a lot in advance!

Stable Melpa:
* https://stable.melpa.org/#/doom-modeline
* https://stable.melpa.org/#/nerd-icons (does not exist yet)

Files that require `nerd-icons`:
* https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-core.el

CC @seagle0128

**Comment by seagle0128** [comment]
I pushed a tag: 0.1.0.

**Comment by xgqt** [comment]
> I pushed a tag: 0.1.0.

Thanks!
