### ISSUE TITLE
Link to nerd-icons-corfu

### ISSUE THREAD

**Issue by minad** [rainstormstudio/nerd-icons.el#59]
Fyi, there is a new package https://github.com/LuigiPiucco/nerd-icons-corfu. Perhaps remove the section "Use nerd-icons with Corfu"? See also https://github.com/jdtsmith/kind-icon/issues/39.

**Comment by rainstormstudio** [comment]
I'm so sorry to reply to this so late! I just updated the README (95281e35d9402d6b235811cae6d4a8988499c570) and provided a link to nerd-icons-corfu.
