### ISSUE TITLE
Error with use-package?

### ISSUE THREAD

**Issue by sbowman** [rainstormstudio/nerd-icons.el#63]
Sorry if I'm just missing something, but I can't get the `use-package` example to work in my `init.el`.  If I include this:

    (use-package nerd-icons
      ;; :custom
      ;; The Nerd Font you want to use in GUI
      ;; "Symbols Nerd Font Mono" is the default and is recommended
      ;; but you can use any other Nerd Font if you want
      (nerd-icons-font-family "SauceCodePro Nerd Font")
      )

I get this error:

> Error (use-package): Failed to parse package nerd-icons: Wrong type argument: symbolp, (nerd-icons-font-family "SauceCodePro Nerd Font")

If I comment out the `nerd-icons-font-family` line it's ok.  And I've got the SauceCodePro Nerd Font installed in my system (macOS Sonoma, Intel).

**Comment by seagle0128** [comment]
You comment `:custom` keyword in your snippet above.

**Comment by rainstormstudio** [comment]
Please do not comment out `:custom` if you want to modify `nerd-icons-font-family`. Note that `nerd-icons-font-family` is a custom variable, which can be modified in the `:custom` section of `use-package`.

Basically it should look like this if you want to modify the font:
```emacs-lisp
(use-package nerd-icons
  :custom
  ;; The Nerd Font you want to use in GUI
  ;; "Symbols Nerd Font Mono" is the default and is recommended
  ;; but you can use any other Nerd Font if you want
  (nerd-icons-font-family "SauceCodePro Nerd Font")
  )
```

**Comment by sbowman** [comment]
Doh...sorry.  Can't believe I missed that.
