### ISSUE TITLE
misplaced icon (e6b1)

### ISSUE THREAD

**Issue by xmathe** [rainstormstudio/nerd-icons.el#64]
With last update nerd-icons.el line 203 stated:
  `  ("lisp"           nerd-icons-mdicon "nf-custom-scheme"      :face nerd-icons-orange)`

Icon nf-custom-scheme belongs to  'nerd-icons-sucicon' cluster.

Thanks for your work.

**Comment by rainstormstudio** [comment]
Thank you for pointing this out :) I just fixed it.
