### ISSUE TITLE
how can I force all icons in the same color

### ISSUE THREAD

**Issue by ydzhou** [rainstormstudio/nerd-icons.el#80]
I want to use the same color for all the icons on treemacs and dired. Is there a easy way to do that instead of overriding every icons in alist?

**Comment by seagle0128** [comment]
`(setq nerd-icons-color-icons nil)`.

**Comment by ydzhou** [comment]
Nope not working.. the treemacs icons are still colorful

**Comment by ydzhou** [comment]
Okay dired one is working... do you know how to make it work for treemacs?

**Comment by seagle0128** [comment]
> Okay dired one is working... do you know how to make it work for treemacs?

You should use `treemacs-nerd-icons`.

``` emacs-lisp
(use-package treemacs-nerd-icons
    :demand t
    :config (treemacs-load-theme "nerd-icons"))
```

**Comment by ydzhou** [comment]
Yes. I am using treemacs-nerd-icons. But it is not respecting `nerd-icons-color-icons`

**Comment by ydzhou** [comment]
I'll open a new issue in treemacs-nerd-icons then

**Comment by seagle0128** [comment]
I don't think so. In my env, `treemacs-nerd-icons` respects `nerd-icons-color-icons`.

<img width="1317" alt="image" src="https://github.com/rainstormstudio/nerd-icons.el/assets/140797/141b4aef-a38b-4c31-9b10-3ab00cf0f19b">

**Comment by ydzhou** [comment]
Yeah it's a mistake in my config. It is working now. The nerd-icon config has to be loaded before I load my treemacs-nerd-icon theme. Thanks!
