### ISSUE TITLE
nerd-icons with Emacs in Terminal

### ISSUE THREAD

**Issue by dr-scsi** [rainstormstudio/nerd-icons.el#86]
Many thanks for this package 🙏 

I'm running the latest package (nerd-icons-20240524.311) from MELPA with Emacs 31.0.50 on macOS.  The nerd-fonts are installed via homebrew and everything works fine with GUI-Emacs, but not in Terminal.  These are 2 snapshots recorded with `emacs -Q` and `emacs -nw -Q` followed by eval'ing this in scratch:

```
(progn
  (package-initialize t)
  (package-activate 'nerd-icons))

```
Running `M-x nerd-icons-insert-codicon TAB` gives this for GUI:
<img width="436" alt="emacs-gui" src="https://github.com/rainstormstudio/nerd-icons.el/assets/59777257/3679eeb7-0c7a-4457-abf9-aef26c95f294">
and this in Terminal:
<img width="468" alt="emacs-terminal" src="https://github.com/rainstormstudio/nerd-icons.el/assets/59777257/8a512613-6273-41f4-be5c-04321d12ddad">

Am I missing something?  I thought nerd-icons would work in terminal.

**Comment by seagle0128** [comment]
You should configure the terminal to display with nerd fonts.

**Comment by seagle0128** [comment]
You should configure the terminal to display with nerd fonts.

**Comment by dr-scsi** [comment]
Thanks for your response.   I use iTerm2 and had to tweak the `Settings -> Profiles -> Text` and check the box for `Use a different font for non-ASCII text`.  But it is not really satisfactory; I have to play with `Manage Special Exceptions`, I guess.  At any rate, I'm closing this report since it looks like a cockpit error; sorry for the noise.

**Comment by seagle0128** [comment]
@dr-scsi I am using iTerm as well, with `font-hack-nerd-font`. It's working well.

**Comment by dr-scsi** [comment]
@seagle0128 - I'm using SourceCodePro (unpatched) and Symbols Nerd Fonts.  I fixed the issue by adding the relevant character point ranges to the exception list under `Settings -> Profiles -> Text` which I picked up from [this script](https://github.com/ryanoasis/nerd-fonts/blob/11ab9428938a6ecbd8d308d6d552d767db6046cc/bin/scripts/test-fonts.sh#L139).  I have to fix range for Material Design, but otherwise I get the icons in terminal.

**Comment by seagle0128** [comment]
@dr-scsi FYI. This is mine

<img width="589" alt="image" src="https://github.com/rainstormstudio/nerd-icons.el/assets/140797/ffd99e84-dd33-4daf-9c6b-f629ab584b84">

**Comment by dr-scsi** [comment]
@seagle0128 - This is my setup:
<img width="561" alt="snapshot-1" src="https://github.com/rainstormstudio/nerd-icons.el/assets/59777257/8b8b4bda-3640-4ff6-a86b-c7bcac8a62af">

I have this under `Manage Special Exceptions`:
<img width="476" alt="snapshot-2" src="https://github.com/rainstormstudio/nerd-icons.el/assets/59777257/e2350773-55e3-43a8-8640-680abad82883">

The entries look like this:
<img width="381" alt="snapshot-3" src="https://github.com/rainstormstudio/nerd-icons.el/assets/59777257/e7320b7b-d1dd-4f7e-9c15-89ec5443961b">
