### ISSUE TITLE
Missing icon for Matlab files

### ISSUE THREAD

**Issue by vcurdia** [rainstormstudio/nerd-icons.el#89]
I have been using Nerd-Icons for a little while but noticed recently that all the ".m" files are showing the Apple logo instead of the Matlab logo. The latter is what I am interested in. The All the Icons package has the Matlab icon, but apparently I cannot find the equivalent using Nerd Icons. 

Does anyone know the solution to this?

Thanks

**Comment by seagle0128** [comment]
Please file an issue for [nerd fonts](https://github.com/ryanoasis/nerd-fonts) first.

**Comment by vcurdia** [comment]
OK
